version: 2

models:
  - name: customers_test
    description: This table contains all customer records
    columns:
      - name: id
        description: Unique identifier for each customer
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name

      - name: orders
        description: This table contains all order records
        columns:
          - name: order_id
            description: Unique identifier for each order
            tests:
              - unique
              - not_null
          - name: user_id
          - name: order_date
          - name: status
          # add other columns here...

      - name: payments
        description: This table contains all payment records
        columns:
          - name: payment_id
            description: Unique identifier for each payment
            tests:
              - unique
              - not_null
          - name: order_id
          - name: payment_method
          - name: amount
      # add other columns here...